### ISSUE TITLE
Error in findDeclaration: TypeError: Cannot read properties of undefined (reading 'ast')

### ISSUE THREAD

**Issue by xcarpentier** [chakra-ui/eslint-plugin-panda#183]
Hi,

Thanks for this helpful linter package ! 

- Warning message when execution the next lint
- some context:
  - yarn workspace
  - next project
- Version 0.2.0
- Here the stacktrace
```
Error in findDeclaration: TypeError: Cannot read properties of undefined (reading 'ast')
    at findDeclaration (ROOT/node_modules/@pandacss/eslint-plugin/dist/index.js:8088:72)
    at isLocalStyledFactory (ROOT/node_modules/@pandacss/eslint-plugin/dist/index.js:8102:16)
    at isPandaProp (ROOT/node_modules/@pandacss/eslint-plugin/dist/index.js:8131:39)
    at JSXAttribute (ROOT/node_modules/@pandacss/eslint-plugin/dist/index.js:8735:14)
    at ROOT/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (ROOT/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (ROOT/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (ROOT/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (ROOT/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
```

**Comment by anubra266** [comment]
@xcarpentier Could you share what code was being linted if you don't mind? thanks
