### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by theMasix** [chakra-ui/eslint-plugin-panda#52]
Error:

```txt
TypeError: Cannot read properties of undefined (reading 'forEach')
Occurred while linting /path/to/project/src/components/Accordion/Accordion.stories.tsx:59
Rule: "@pandacss/no-invalid-token-paths"
    at Referencer.visitFunction (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:7326:28)
    at Referencer.ArrowFunctionExpression (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:7359:14)
    at Referencer.visit (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:6420:19)
    at Referencer.visitProperty (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:7343:14)
    at Referencer.Property (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:7532:14)
    at Referencer.visit (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:6420:19)
    at Referencer.visitChildren (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:6403:22)
    at Referencer.visit (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:6425:14)
    at Referencer.VariableDeclaration (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:7623:16)
    at Referencer.visit (/path/to/project/node_modules/.pnpm/@pandacss+eslint-plugin@0.1.1_eslint@8.57.0_typescript@5.1.6/node_modules/@pandacss/eslint-plugin/dist/index.js:6420:19)
 ELIFECYCLE  Command failed with exit code 2.
```
Code of `Accordion/Accordion.stories.tsx`:

```tsx
/**
 * Curve accordion type and first accordion is opened.
 */
export const MultipleWithDefaultValue: Story = {
  render: (args, { globals: { locale } }) => (
    <Accordion {...args}>
      <AccordionItem value='accordion1'>
        <AccordionItemHeader>{child[locale]}</AccordionItemHeader>
        <AccordionItemContent>{contentChild[locale]}</AccordionItemContent>
      </AccordionItem>
      <AccordionItem value='accordion2'>
        <AccordionItemHeader>{child[locale]}</AccordionItemHeader>
        <AccordionItemContent>{contentChild[locale]}</AccordionItemContent>
      </AccordionItem>
    </Accordion>
  ),
  args: {
    defaultValue: ['accordion1'],
    multiple: true,
    variant: 'curve',
  },
};
```

<img width="803" alt="Screenshot 2024-03-26 at 19 58 43" src="https://github.com/chakra-ui/eslint-plugin-panda/assets/22872117/d70a97fa-8024-47d9-8fb2-9f0a715e6921">

---

### Environments

```txt
    "@pandacss/eslint-plugin": "^0.1.1",
    "@pandacss/dev": "^0.36.1",
    "typescript": "^5.1.6",
    "eslint": "^8.57.0",
```

**Comment by anubra266** [comment]
@theMasix I can't reproduce this. And I don't seem to see any panda usage in this file. Any more information you think could be helpful?

**Comment by drphelps** [comment]
@anubra266 I managed to reproduce this [here](https://codesandbox.io/p/devbox/spring-morning-hqlkpv).

**Comment by drphelps** [comment]
@theMasix here's a simpler [reproduction](https://github.com/drphelps/pandacss-example/tree/main). It seems that the inclusion of `@babel/eslint-parser` causes the issue.

**Comment by anubra266** [comment]
You're right @drphelps, @theMasix, Unfortunately this is not something we can fix on our end. 

>since @typescript-eslint uses TypeScript under the hood, its rules can be made type-aware, which is something Babel doesn't have the ability to do.
https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser#typescript

If your project is a pure TS project, just use `@typescript-eslint`

But If your project has both TS and JS, you can use @babel/eslint-parser as well through `overrides`

```js
{
  parser: "@babel/eslint-parser",
  overrides: [
    {
      "files": ["*.{ts,tsx}"],
      "parser": "@typescript-eslint/parser",
    }
  ],
}
```
